services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    hostname: homepage.docker
    restart: unless-stopped
    ports:
      - 192.168.74.212:3001:3000
    volumes:
      - /mnt/gluster_ha/01-docker-volumes/homepage/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations, see alternative methods
    environment:
      - PUID=1000
      - PGID=1000
      - HOMEPAGE_ALLOWED_HOSTS=home.bitforge.pl
    networks:
      - docker_shared_net
    tty: true
networks:
  docker_shared_net:
    external: true
